language: python
python:
    - "3.5"
services:
    - postgresql
install: "pip install -r requirements.txt"
before_script:
    - psql -c 'create database test;' -U postgres
env:
    - DATABASE_URL=postgres://postgres@localhost:5432/test SECRET_KEY=testing DEBUG=True
script:
    - cd bjjtourneyfinder
    - printenv
    - python manage.py test
