version: '2'
services:
    db:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
    api:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        links:
            - db
        env_file:
            - ./secret_env/local.env
        environment:
            - DB_ADDR=db
