# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usrtoken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 1, 18, 15, 4, 418329, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 1, 18, 15, 4, 418329, tzinfo=utc)),
        ),
    ]
