# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('T', 'Tournament'), ('S', 'Seminar')], default='T', max_length=1),
        ),
    ]
