# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20161017_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 7, 14, 59, 48, 855348, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 7, 14, 59, 56, 118651, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
